### ISSUE TITLE
running default dataset results in either "NVIDIA gpu not found" or "GLIBCXX_3.4.21" not found

### ISSUE THREAD

**Issue by paulaberry** [FTD007/PInet#2]
When running the command (note in Readme.md the test command appears to be missing a second `-` in front of `dataset`)  ` python utils/train_richdbd2_fixed6mmgk.py --dataset dbd` This appears when running on a local machine:

```
Namespace(batchSize=16, bs2=8, class_choice='protein', dataset='dbd', drop=0, fac=100, feature_transform=False, fold='', ft=0, indim=5, l='ligand', lloss=1, model='', nepoch=25, npoints=20000, outf='seg', r='recept', rs=0, start=10, workers=0)
Random Seed:  5902
{'recept': 0}
{'protein': 2, 'ligand': 2, 'recept': 2} 2
{'ligand': 0}
{'protein': 2, 'ligand': 2, 'recept': 2} 2
{'recept': 0}
{'protein': 2, 'ligand': 2, 'recept': 2} 2
{'ligand': 0}
{'protein': 2, 'ligand': 2, 'recept': 2} 2
0 0
classes 2
1 1
classes 2
Traceback (most recent call last):
  File "utils/train_richdbd2_fixed6mmgk.py", line 168, in <module>
    classifier.cuda()
  File "/home/pberry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/pberry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/pberry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/pberry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/pberry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/home/pberry/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/home/pberry/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

And when attempting to run it on a shared linux server:

```
Traceback (most recent call last):
  File "utils/train_richdbd2_fixed6mmgk.py", line 16, in <module>
    from sklearn.metrics import precision_score,recall_score,roc_curve,auc
  File "/home/pb2471/anaconda3/lib/python3.8/site-packages/sklearn/__init__.py", line 80, in <module>
    from .base import clone
  File "/home/pb2471/anaconda3/lib/python3.8/site-packages/sklearn/base.py", line 21, in <module>
    from .utils import _IS_32BIT
  File "/home/pb2471/anaconda3/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 20, in <module>
    from scipy.sparse import issparse
  File "/home/pb2471/anaconda3/lib/python3.8/site-packages/scipy/__init__.py", line 155, in <module>
    from . import fft
  File "/home/pb2471/anaconda3/lib/python3.8/site-packages/scipy/fft/__init__.py", line 74, in <module>
    from ._basic import (
  File "/home/pb2471/anaconda3/lib/python3.8/site-packages/scipy/fft/_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "/home/pb2471/anaconda3/lib/python3.8/site-packages/scipy/_lib/uarray.py", line 28, in <module>
    from ._uarray import *
  File "/home/pb2471/anaconda3/lib/python3.8/site-packages/scipy/_lib/_uarray/__init__.py", line 115, in <module>
    from ._backend import *
  File "/home/pb2471/anaconda3/lib/python3.8/site-packages/scipy/_lib/_uarray/_backend.py", line 4, in <module>
    from . import _uarray  # type: ignore
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/pb2471/anaconda3/lib/python3.8/site-packages/scipy/_lib/_uarray/_uarray.cpython-38-x86_64-linux-gnu.so)
```

**Comment by FTD007** [comment]
could you try `nvidia-smi` checking version of your GPU and `nvcc --version` for cuda?
