### ISSUE TITLE
ValueError: could not convert string to float: 'REMARK'`

### ISSUE THREAD

**Issue by NataZen** [FTD007/PInet#3]
This appears when running `python PreProcessLifeSavor.py 2I25-l.pdb 2I25-r.pdb`:
```
Traceback (most recent call last):
  File "/home/ant/data/PInet/utils/PreProcessLifeSavor.py", line 162, in <module>
    gl, orl, dl, vl = parsefile(apbsl)
  File "/home/ant/data/PInet/utils/dx2feature.py", line 41, in parsefile
    value.extend([float(d) for d in line.strip().split(' ')])
  File "/home/ant/data/PInet/utils/dx2feature.py", line 41, in <listcomp>
    value.extend([float(d) for d in line.strip().split(' ')])
ValueError: could not convert string to float: 'REMARK'
```

* Which APBS version are you using?
* Where to get the files `pdbfile_l[0:4]+'-l.pqr.dx','r'` and `pdbfile_l[0:4]+'-r.pqr.dx','r'`? Format .pqr.dx is the same as format .pqr?

**Comment by FTD007** [comment]
the APBS version should be 2.
so that .pqr is the output of PDB2PQR and .pqr.dx is the output of APBS
